name: Build

on:
  push:
  pull_request:

jobs:
  build-cmake:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Prepare the system (Linux)
      if: contains(matrix.os, 'ubuntu')
      run: |
        sudo scripts/prepare-system.sh

    - name: Build and install
      run: scripts/install.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: machines-data
        path: ${{github.workspace}}/install/machines
